// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MyTestViajanet.Infra.Data.Contexto;
using System;

namespace MyTestViajanet.Infra.Data.Migrations
{
    [DbContext(typeof(MyTestViajanetContexto))]
    partial class MyTestViajanetContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyTestViajaNet.DomainService.Entities.BatePapoOnline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataCadastro");

                    b.Property<DateTime>("DataRegistro");

                    b.Property<string>("LugaresDisponiveis");

                    b.Property<string>("PessoasOnline");

                    b.HasKey("Id");

                    b.ToTable("BatePapoOnline");
                });

            modelBuilder.Entity("MyTestViajaNet.DomainService.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo");

                    b.Property<string>("Cpf");

                    b.Property<DateTime>("DataCadastro");

                    b.Property<DateTime>("DataExpiracao");

                    b.Property<string>("Email");

                    b.Property<bool>("Logado");

                    b.Property<string>("Login");

                    b.Property<string>("Nome")
                        .HasMaxLength(200);

                    b.Property<string>("Senha");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
